// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: computedavg.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Computedavg {
  public static partial class ComputedAvgService
  {
    static readonly string __ServiceName = "computedavg.ComputedAvgService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Computedavg.NumberXRequest> __Marshaller_computedavg_NumberXRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Computedavg.NumberXRequest.Parser));
    static readonly grpc::Marshaller<global::Computedavg.NumberXResponse> __Marshaller_computedavg_NumberXResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Computedavg.NumberXResponse.Parser));

    static readonly grpc::Method<global::Computedavg.NumberXRequest, global::Computedavg.NumberXResponse> __Method_ComputeAvg = new grpc::Method<global::Computedavg.NumberXRequest, global::Computedavg.NumberXResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "ComputeAvg",
        __Marshaller_computedavg_NumberXRequest,
        __Marshaller_computedavg_NumberXResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Computedavg.ComputedavgReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ComputedAvgService</summary>
    [grpc::BindServiceMethod(typeof(ComputedAvgService), "BindService")]
    public abstract partial class ComputedAvgServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Computedavg.NumberXResponse> ComputeAvg(grpc::IAsyncStreamReader<global::Computedavg.NumberXRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ComputedAvgService</summary>
    public partial class ComputedAvgServiceClient : grpc::ClientBase<ComputedAvgServiceClient>
    {
      /// <summary>Creates a new client for ComputedAvgService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ComputedAvgServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ComputedAvgService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ComputedAvgServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ComputedAvgServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ComputedAvgServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncClientStreamingCall<global::Computedavg.NumberXRequest, global::Computedavg.NumberXResponse> ComputeAvg(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeAvg(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Computedavg.NumberXRequest, global::Computedavg.NumberXResponse> ComputeAvg(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_ComputeAvg, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ComputedAvgServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ComputedAvgServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ComputedAvgServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ComputeAvg, serviceImpl.ComputeAvg).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ComputedAvgServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ComputeAvg, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Computedavg.NumberXRequest, global::Computedavg.NumberXResponse>(serviceImpl.ComputeAvg));
    }

  }
}
#endregion
