// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: maxnumber.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Maxnumber {
  public static partial class MaxNumberService
  {
    static readonly string __ServiceName = "maxnumber.MaxNumberService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Maxnumber.RandomNumberRequest> __Marshaller_maxnumber_RandomNumberRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Maxnumber.RandomNumberRequest.Parser));
    static readonly grpc::Marshaller<global::Maxnumber.MaxNumberResponse> __Marshaller_maxnumber_MaxNumberResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Maxnumber.MaxNumberResponse.Parser));

    static readonly grpc::Method<global::Maxnumber.RandomNumberRequest, global::Maxnumber.MaxNumberResponse> __Method_GetMaxNumber = new grpc::Method<global::Maxnumber.RandomNumberRequest, global::Maxnumber.MaxNumberResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GetMaxNumber",
        __Marshaller_maxnumber_RandomNumberRequest,
        __Marshaller_maxnumber_MaxNumberResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Maxnumber.MaxnumberReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MaxNumberService</summary>
    [grpc::BindServiceMethod(typeof(MaxNumberService), "BindService")]
    public abstract partial class MaxNumberServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetMaxNumber(grpc::IAsyncStreamReader<global::Maxnumber.RandomNumberRequest> requestStream, grpc::IServerStreamWriter<global::Maxnumber.MaxNumberResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MaxNumberService</summary>
    public partial class MaxNumberServiceClient : grpc::ClientBase<MaxNumberServiceClient>
    {
      /// <summary>Creates a new client for MaxNumberService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MaxNumberServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MaxNumberService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MaxNumberServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MaxNumberServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MaxNumberServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Maxnumber.RandomNumberRequest, global::Maxnumber.MaxNumberResponse> GetMaxNumber(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMaxNumber(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Maxnumber.RandomNumberRequest, global::Maxnumber.MaxNumberResponse> GetMaxNumber(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GetMaxNumber, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MaxNumberServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MaxNumberServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MaxNumberServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMaxNumber, serviceImpl.GetMaxNumber).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MaxNumberServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetMaxNumber, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Maxnumber.RandomNumberRequest, global::Maxnumber.MaxNumberResponse>(serviceImpl.GetMaxNumber));
    }

  }
}
#endregion
