// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: primenumber.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Primenumber {
  public static partial class PrimeNumberService
  {
    static readonly string __ServiceName = "primenumber.PrimeNumberService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Primenumber.PrimeNumberRequest> __Marshaller_primenumber_PrimeNumberRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Primenumber.PrimeNumberRequest.Parser));
    static readonly grpc::Marshaller<global::Primenumber.PrimeNumberResponse> __Marshaller_primenumber_PrimeNumberResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Primenumber.PrimeNumberResponse.Parser));

    static readonly grpc::Method<global::Primenumber.PrimeNumberRequest, global::Primenumber.PrimeNumberResponse> __Method_CalculatePrimeNumber = new grpc::Method<global::Primenumber.PrimeNumberRequest, global::Primenumber.PrimeNumberResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "CalculatePrimeNumber",
        __Marshaller_primenumber_PrimeNumberRequest,
        __Marshaller_primenumber_PrimeNumberResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Primenumber.PrimenumberReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PrimeNumberService</summary>
    [grpc::BindServiceMethod(typeof(PrimeNumberService), "BindService")]
    public abstract partial class PrimeNumberServiceBase
    {
      public virtual global::System.Threading.Tasks.Task CalculatePrimeNumber(global::Primenumber.PrimeNumberRequest request, grpc::IServerStreamWriter<global::Primenumber.PrimeNumberResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PrimeNumberService</summary>
    public partial class PrimeNumberServiceClient : grpc::ClientBase<PrimeNumberServiceClient>
    {
      /// <summary>Creates a new client for PrimeNumberService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PrimeNumberServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PrimeNumberService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PrimeNumberServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PrimeNumberServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PrimeNumberServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Primenumber.PrimeNumberResponse> CalculatePrimeNumber(global::Primenumber.PrimeNumberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculatePrimeNumber(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Primenumber.PrimeNumberResponse> CalculatePrimeNumber(global::Primenumber.PrimeNumberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_CalculatePrimeNumber, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PrimeNumberServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PrimeNumberServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PrimeNumberServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CalculatePrimeNumber, serviceImpl.CalculatePrimeNumber).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PrimeNumberServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CalculatePrimeNumber, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Primenumber.PrimeNumberRequest, global::Primenumber.PrimeNumberResponse>(serviceImpl.CalculatePrimeNumber));
    }

  }
}
#endregion
